FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY prep_data.py .

CMD ["python", "prep_data.py", "--n_samples", "1000", "--output_file", "data.csv"]
