FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY train_model.py .

CMD ["python", "train_model.py", "--model_name=model.txt", "--dataset_path=data.csv"]
